version: "3.8"
volumes:
  buckets:
services:
  spark-hive:
    container_name: spark-hive
    image: spark-hive
    build:
      context: ..
      dockerfile: docker/Dockerfile_Spark_HiveThriftServer2
    ports:
      - "10001:10001"
      - "4040:4040"
    environment:
      - AUTH_DOMAIN=garner.auth0.com
      - AUTH_CLIENT_ID=1GqAdLq4L6FtOcpFVUfcyO1kqFD7bmvq
      - AUTH_CLIENT_SECRET=iV09kSY1kaZ_BFSaCkHC9fHeW5KMuQ_jIvkV2JIrA6r0p2oi649LyRwpbfNBZlrU
      - SPARK_HOME=/opt/spark
      - DUMMY_EXTERNALS_LOCATION=${SPARK_HOME}/externals
      - BEELINE_CLASS=org.apache.hive.beeline.BeeLine
      - LIGHTHOUSE_URL=http://${DOCKER_GATEWAY_HOST:-host.docker.internal}:9000/graph-ql
      - LOCAL_AUTH_EMAIL=lighthouse-root@garnercorp.com
      - LOCAL_AUTH_PASSWORD=JR8aA1@Ra/u/ksoZSsd2u9koBG/UjgKT
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - spark-master
  spark-master:
    container_name: spark-master
    image: spark-master
    build:
      context: ..
      dockerfile: docker/Dockerfile_Spark_Master
    ports:
      - '8080:8080'
    environment:
      - SPARK_HOME=/opt/spark
      - DUMMY_EXTERNALS_LOCATION=${SPARK_HOME}/externals
  spark-worker-1:
    container_name: spark-worker-1
    image: spark-worker
    build:
      context: ..
      dockerfile: docker/Dockerfile_Spark_Worker
    environment:
      - SPARK_HOME=/opt/spark
      - DUMMY_EXTERNALS_LOCATION=${SPARK_HOME}/externals
      - SPARK_MASTER_URL=spark://spark-master:7077
      - LIGHTHOUSE_URL=http://${DOCKER_GATEWAY_HOST:-host.docker.internal}:9000/graph-ql
      - STUBLOCAL=FALSE
      - STUB_PASSWORD=JR8aA1@Ra/u/ksoZSsd2u9koBG/UjgKT
      - STUB_USERNAME=lighthouse-root@garnercorp.com
      - AUTH_DOMAIN=garner.auth0.com
      - AUTH_CLIENT_ID=1GqAdLq4L6FtOcpFVUfcyO1kqFD7bmvq
      - AUTH_CLIENT_SECRET=iV09kSY1kaZ_BFSaCkHC9fHeW5KMuQ_jIvkV2JIrA6r0p2oi649LyRwpbfNBZlrU
    depends_on:
      - spark-master
