version: "3.8"
volumes:
  buckets:
services:
  spark-hive-admin:
    container_name: spark-hive-admin
    image: spark-hive
    build:
      context: ..
      dockerfile: docker/Dockerfile_Spark_HiveThriftServer2
    ports:
      - "10002:10002"
      - "4040:4040"
    environment:
      - SPARK_METASTORE_URL=jdbc:postgresql://spark-postgres-metastore-1:5432/postgres?createDatabaseIfNotExist=true;autoReconnect=true;useSSL=false
      - METASTORE_USER=postgres
      - METASTORE_PASSWORD=Password1!
      - HIVE_SERVER_PORT=10002
      - AUTH_DOMAIN=garner.auth0.com
      - AUTH_CLIENT_ID=1GqAdLq4L6FtOcpFVUfcyO1kqFD7bmvq
      - AUTH_CLIENT_SECRET=iV09kSY1kaZ_BFSaCkHC9fHeW5KMuQ_jIvkV2JIrA6r0p2oi649LyRwpbfNBZlrU
      - SPARK_HOME=/opt/spark
      - DUMMY_EXTERNALS_LOCATION=${SPARK_HOME}/externals
      - BEELINE_CLASS=org.apache.hive.beeline.BeeLine
      - LIGHTHOUSE_URL=http://${DOCKER_GATEWAY_HOST:-host.docker.internal}:9000/graph-ql
      - LOCAL_AUTH_EMAIL=lighthouse-root@garnercorp.com
      - LOCAL_AUTH_PASSWORD=JR8aA1@Ra/u/ksoZSsd2u9koBG/UjgKT
      - SPARK_MASTER_URL=spark://spark-master:7077
      - PARTY_MEASURE_TABLE=Platform
      - PROD_MAX_PAGES=1
      - PROD_MAX_PAGE_SIZE=10
      - SPARK_EXECUTOR_MEMORY=1g
    depends_on:
      - spark-master
  spark-hive-client:
    container_name: spark-hive-client
    image: spark-hive
    build:
      context: ..
      dockerfile: docker/Dockerfile_Spark_HiveThriftServer2
    ports:
      - "10001:10001"
    environment:
      - SPARK_METASTORE_URL=jdbc:postgresql://spark-postgres-metastore-1:5432/postgres?createDatabaseIfNotExist=true;autoReconnect=true;useSSL=false
      - METASTORE_USER=clienthive
      - METASTORE_PASSWORD=Password2!
      - HIVE_SERVER_PORT=10001
      - AUTH_DOMAIN=garner.auth0.com
      - AUTH_CLIENT_ID=1GqAdLq4L6FtOcpFVUfcyO1kqFD7bmvq
      - AUTH_CLIENT_SECRET=iV09kSY1kaZ_BFSaCkHC9fHeW5KMuQ_jIvkV2JIrA6r0p2oi649LyRwpbfNBZlrU
      - SPARK_HOME=/opt/spark
      - DUMMY_EXTERNALS_LOCATION=${SPARK_HOME}/externals
      - BEELINE_CLASS=org.apache.hive.beeline.BeeLine
      - LIGHTHOUSE_URL=http://${DOCKER_GATEWAY_HOST:-host.docker.internal}:9000/graph-ql
      - LOCAL_AUTH_EMAIL=lighthouse-root@garnercorp.com
      - LOCAL_AUTH_PASSWORD=JR8aA1@Ra/u/ksoZSsd2u9koBG/UjgKT
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_EXECUTOR_MEMORY=2g
    depends_on:
      - spark-master
  spark-master:
    container_name: spark-master
    image: spark-master
    build:
      context: ..
      dockerfile: docker/Dockerfile_Spark_Master
    ports:
      - '8080:8080'
    environment:
      - SPARK_HOME=/opt/spark
      - DUMMY_EXTERNALS_LOCATION=${SPARK_HOME}/externals
  spark-worker-1:
    container_name: spark-worker-1
    image: spark-worker
    build:
      context: ..
      dockerfile: docker/Dockerfile_Spark_Worker
    environment:
      - SPARK_HOME=/opt/spark
      - DUMMY_EXTERNALS_LOCATION=${SPARK_HOME}/externals
      - SPARK_MASTER_URL=spark://spark-master:7077
      - LIGHTHOUSE_URL=http://${DOCKER_GATEWAY_HOST:-host.docker.internal}:9000/graph-ql
      - AUTH_DOMAIN=garner.auth0.com
      - PARTY_MEASURE_TABLE=Platform
      - MAX_PAGES=1000
      - MAX_PAGE_SIZE=50
    depends_on:
      - spark-master
  spark-postgres-metastore-1:
    container_name: spark-postgres-metastore-1
    image: spark-postgres
    build:
      context: ..
      dockerfile: docker/Dockerfile_Postgres
    environment:
      - POSTGRES_PASSWORD=Password1!
    ports:
      - '5432:5432'
  spark-pgadmin:
    container_name: spark-pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.local
      - PGADMIN_DEFAULT_PASSWORD=Password1!
    ports:
    - '80:80'
  spark-maintainer:
      container_name: spark-maintainer
      image: spark-maintainer
      build:
        context: ..
        dockerfile: docker/Dockerfile_Spark_Garner_Maintainer
  spark-maintainer-base:
      container_name: spark-maintainer-base
      image: spark-maintainer-base
      build:
        context: ..
        dockerfile: docker/Dockerfile_Spark_Garner_Maintainer_Base
  spark-base:
    container_name: spark-base
    image: spark-base
    build:
      context: ..
      dockerfile: docker/Dockerfile_Spark_Base

